import Head from 'next/head';
import { Inter } from "next/font/google";
import "../styles/globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ideas-Drone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/Logo_main.png" type="image/png"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </Head>
        <body className={inter.className}>
          {children}
        </body>
    </html>
  );
}

